---
config:
  name: vs-foo.bar.org
  destination: 192.168.1.1
  port: 443
  partition: Common
  state: present
  irules: 
    - _sys_https_redirect
  profiles:
    -  http
    - context: client-side
      name: clientsslpf-foo.bar.org
    - context: server-side
      name: serverssl-foo.bar.org
  snat: automap
  pool: ""
